name: CI

on:
  push:
    branches: [master]
    paths:
      - "src/**"
      - "vite.config.ts"
      - "vitest.config.ts"
      - "tsconfig.json"
      - "package.json"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [master]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: TypeScript check
        run: pnpm run tsc

      - name: Format check
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test
